use renderer::prelude::*;

#[test]
fn test_draw_sphere() {
    let scene = Scene::new(
        vec![Box::new(Sphere::new(
            Vector3D::new(0.0, 0.0, 0.0),
            5.0,
            Coloring::Fill(Color::WHITE),
        ))],
        Camera::new(
            Vector3D::new(0.0, 0.0, -20.0),
            Direction::new(Vector3D::new(0.0, 1.0, 0.0), Vector3D::new(1.0, 0.0, 0.0)),
            Screen::new(Dimensions::new(64, 48)),
            10.0,
        ),
    );
    let image = scene.render();

    assert_eq!(
        format!("{}", image),
        r#"................
................
......xxxxx.....
.....xxxxxxx....
....xxxxxxxxx...
....xxxxxxxxx...
....xxxxxxxxx...
....xxxxxxxxx...
....xxxxxxxxx...
.....xxxxxxx....
......xxxxx.....
................
"#
    );
}
